# Generated by Django 4.2.7 on 2023-11-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
